name: DockerHub Publish - Dev

on:
  push:
    branches:
      - master
    tags:
      - dev
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/dockerhub-push.yml
    secrets: inherit
    with:
      tag: 'dev'
