name: DockerHub Publish

on:
  workflow_call:
    inputs:
      tag:
        description: 'A Docker Image Tag'
        default: 'latest'
        required: false
        type: string
      version:
        description: "A version of the Application"
        default: "0.0.1"
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: vshefer/chessgrinder:${{ inputs.tag }}
          build-args: |
            VERSION=${{ inputs.version }}
